# Generated by Django 4.2.3 on 2023-07-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_users', 'can_view_users'), ('can_block_users', 'can_block_users')]},
        ),
    ]
