# Generated by Django 4.2.3 on 2023-07-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_client_owner_mailing_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_view_mailings', 'can_view_mailings'), ('can_disable_mailings', 'can_disable_mailings')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
