# Generated by Django 4.2.3 on 2023-07-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
